### ISSUE TITLE
Nicole - Button bugs

### ISSUE THREAD

**Issue by NikkiHmltn** [NikkiHmltn/textRPG#2]
<img width="952" alt="Screen Shot 2020-11-02 at 9 44 29 AM" src="https://user-images.githubusercontent.com/65046641/97901034-6fe5ec00-1cf0-11eb-8ab2-4a43741b2d36.png">

- [ ] CSS/HTML is messing up my layout after I added my start button

- [ ] My two functions aren't displaying when clicked, they're just automatically displaying depending on the order of the functions listed. I do have an event listener attached to them.

**Comment by pmacaluso3** [comment]
The closing `</button>` tag for the start-game button is a `</div>` tag instead! It took me a second to find it, but I got there by looking at it in dev tools.
